### ISSUE TITLE
Question about experiment

### ISSUE THREAD

**Issue by CxyCH** [vita-epfl/CrowdNav#11]
Hi:
   The segway is a differential drive robot, but your paper assumes the robot is holonomic? So what is the difference between these two kinematic modes in your method?

**Comment by ChanganVR** [comment]
In the paper, we experimented on holonomic mode. When we deployed our algorithm on the robot, we found the kinematics is different. So we added another unicycle kinematic mode in the library. So the actual policy we deployed was trained under similar kinematic to the robot. You can switch kinematic mode by setting kinematics = holonomic in policy.config.

**Comment by JiayunjieJYJ** [comment]
> In the paper, we experimented on holonomic mode. When we deployed our algorithm on the robot, we found the kinematics is different. So we added another unicycle kinematic mode in the library. So the actual policy we deployed was trained under similar kinematic to the robot. You can switch kinematic mode by setting kinematics = holonomic in policy.config.

How to run a unicycle kinematic mode ORCA in your code? Thanks!

**Comment by ChanganVR** [comment]
@JiayunjieJYJ You can't. ORCA has a fixed holonomic setting. You can change the setting for the robot in the config file though.

**Comment by JiayunjieJYJ** [comment]
> @JiayunjieJYJ You can't. ORCA has a fixed holonomic setting. You can change the setting for the robot in the config file though.
What will be the impact of changing the configuration file to unicycle kinematic mode? Will the learning-based navigation method be changed to a unicycle kinematic mode, but ORCA-based baselines will not be affected?

**Comment by ChanganVR** [comment]
>What will be the impact of changing the configuration file to unicycle kinematic mode? Will the learning-based navigation method be changed to a unicycle kinematic mode, but ORCA-based baselines will not be affected?

yes, that is true
