### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by heilonli** [vita-epfl/CrowdNav#13]
(py36) hailong@hailong-HP-Compaq-Pro-6300-MT:~/CrowdNav/crowd_nav$ python train.py --policy sarl
Output directory already exists! Overwrite the folder? (y/n)y
2019-06-26 15:14:04, INFO: Current git head hash code: %s
double free or corruption (!prev)
Aborted (core dumped)
(py36) hailong@hailong-H

**Comment by ChanganVR** [comment]
I have never met this problem under my environment. It seems like your pip doesn't have the package git or there is something wrong with that package, e.g. it's not properly configured. Can you check if you can print the git hash code using git library directly in your terminal?
