### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by liangjiaxuan1018** [vita-epfl/CrowdNav#15]
When I  train a policy,the error as follows：
Output directory already exists! Overwrite the folder? (y/n)n
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main()
  File "train.py", line 57, in main
    repo = git.Repo(search_parent_directories=True)
  File "/home/ljx/anaconda3/envs/CrowdNav/lib/python3.6/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/ljx/桌面/CrowdNav-master/crowd_nav

Is it a problem with the installation package version?

**Comment by liangjiaxuan1018** [comment]
Thank you for your reply.I tried to re-run this program, but I still encountered the following problems:

(CrowdNav) ljx@ljx-ChengMing-3967:~/CrowdNav-master/crowd_nav$ python train.py --policy sarl
Output directory already exists! Overwrite the folder? (y/n)y
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    main()
  File "train.py", line 59, in main
    repo = git.Repo(search_parent_directories=True)
  File "/home/ljx/anaconda3/envs/CrowdNav/lib/python3.6/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/ljx/CrowdNav-master/crowd_nav

Is it a problem with the git package?

**Comment by ChanganVR** [comment]
It looks like something is wrong with the git module. What I can find online is this link: https://github.com/gitpython-developers/GitPython/issues/255. Try it out and see if this error can be fixed. 
In the worse case, you can just comment out these lines of codes, which use the git module. The git module is mainly used for keeping track of code versions when doing development.

**Comment by luxiaojuntokyo** [comment]
I got the same error.
(venv) luxiaojun@luxiaojunP50:~/simulationbase/CrowdNav-master/crowd_nav$ python train.py --policy sarl
Output directory already exists! Overwrite the folder? (y/n)y
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main()
  File "train.py", line 57, in main
    repo = git.Repo(search_parent_directories=True)
  File "/home/luxiaojun/simulationbase/venv/lib/python3.6/site-packages/git/repo/base.py", line 184, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/luxiaojun/simulationbase/CrowdNav-master/crowd_nav

Is there any result in this problem?
Thank you.

**Comment by ChanganVR** [comment]
Did you run the code outside a git repo?

**Comment by luxiaojuntokyo** [comment]
Changan
Thank you for your reply.
When I run "git status" under this directory (~/simulationbase/CrowdNav-master/crowd_nav), “fatal: Not a git repository (or any of the parent directories)” will occur.

Previously, I just download the zip file, extract, build and install.
Now I use git clone and then build and install. The problem didn't apprear.

**Comment by ChanganVR** [comment]
That will be the solution to solve this problem. For other people, if you run into this problem as well, make sure you run the code inside the git repo.

**Comment by asenasen123** [comment]
> When I train a policy,the error as follows：
> Output directory already exists! Overwrite the folder? (y/n)n
> Traceback (most recent call last):
> File "train.py", line 177, in 
> main()
> File "train.py", line 57, in main
> repo = git.Repo(search_parent_directories=True)
> File "/home/ljx/anaconda3/envs/CrowdNav/lib/python3.6/site-packages/git/repo/base.py", line 184, in **init**
> raise InvalidGitRepositoryError(epath)
> git.exc.InvalidGitRepositoryError: /home/ljx/桌面/CrowdNav-master/crowd_nav
> 
> Is it a problem with the installation package version?

你好！我也是这个研究方向，有些问题想要请教，能否价格好友学习交流下，qq:1414396376

**Comment by ChanganVR** [comment]
The git path shouldn't have Chinese characters.

**Comment by asenasen123** [comment]
你好！我是这个方向的研究生。我想请问下，如何在这篇论文代码里训练CADRL以及看到可视化结果，我应该怎么处理？我还有些问题想请教你，能否加下你的微信，18810167835





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Changan Chen"<notifications@github.com&gt;; 
发送时间: 2020年6月7日(星期天) 中午11:44
收件人: "vita-epfl/CrowdNav"<CrowdNav@noreply.github.com&gt;; 
抄送: "夏森"<2940620847@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vita-epfl/CrowdNav] train.py error (#15)





 
The git path shouldn't have Chinese characters.

**Comment by ChanganVR** [comment]
I don't use WeChat that much. If you have questions, I'd recommend you to leave your comments or questions here.

**Comment by asenasen123** [comment]
你好，不好意思打扰了！因为运行cadrl(https://github.com/ChanganVR/CADRL.git)有问题，所以后来我在CrowdNav(https://github.com/vita-epfl/CrowdNav.git)运行cadrl程序。但我发现这两个程序中train_episode不一样（cadrl是1000，CrowdNav=10000）。我想请问下，如果单纯想测试cadrl，可以设置train_episode=1000,会收敛吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Changan Chen"<notifications@github.com&gt;; 
发送时间: 2020年6月10日(星期三) 凌晨5:06
收件人: "vita-epfl/CrowdNav"<CrowdNav@noreply.github.com&gt;; 
抄送: "夏森"<2940620847@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vita-epfl/CrowdNav] train.py error (#15)





 
I don't use WeChat that much. If you have questions, I'd recommend you to leave your comments or questions here.

**Comment by ChanganVR** [comment]
Hi, I don't remember the training parameters for them exactly, but you should definitely try the default first and based on the training/val curve, you can adjust the learning schedule accordingly.
