### ISSUE TITLE
How to set self.kinematics while running CADRL

### ISSUE THREAD

**Issue by Shuijing725** [vita-epfl/CrowdNav#17]
In the CADRL paper by Chen et al, the heading angle of the robot (i.e. self.robot.theta) is part of the robot's state. But the default kinematic of this repo, as defined in crowd_anv/configs/policy.config, is "holonomic", and when kinematic is set to "holonomic", the angle theta never changes throughout an episode (it is always set to 90 degrees). 

So should I set kinematic to "unicycle" while training or testing CADRL?

Thank you a lot!

**Comment by ChanganVR** [comment]
Hi, if I remember correctly, we tested this feature of unicycle kinematics after the submission and it worked. But since we didn't report the results of the unicycle constraint at the time of submission, the default value of kinematics was set to holonomic. 

Please go ahead and use this feature.

**Comment by asenasen123** [comment]
> In the CADRL paper by Chen et al, the heading angle of the robot (i.e. self.robot.theta) is part of the robot's state. But the default kinematic of this repo, as defined in crowd_anv/configs/policy.config, is "holonomic", and when kinematic is set to "holonomic", the angle theta never changes throughout an episode (it is always set to 90 degrees).
> 
> So should I set kinematic to "unicycle" while training or testing CADRL?
> 
> Thank you a lot!

你好！我也是这个方向的研究生，有些问题想要请教，能否加下qq:1414396376,谢谢了
