### ISSUE TITLE
Visible

### ISSUE THREAD

**Issue by tessavdheiden** [vita-epfl/CrowdNav#20]
Hi Changan,

You mentioned that setting the robot to visible lets the robot learn that humans avoid it.

The videos on the readme, are they in the unvisible setting?

**Comment by ChanganVR** [comment]
Yes. And all the results in my paper are evaluated in the invisible setting.

**Comment by anlanxuan** [comment]
Hi Changan,  I have no permission to download your data set and verification set in China. I hope you can provide me with some data.Can you send some data to me?Thanks

**Comment by ChanganVR** [comment]
@anlanxuan There is no data to download except the repo itself. Validation and test set are just different random seeds.

**Comment by anlanxuan** [comment]
Thanks, I mean what is the format of your ORCA data set, is there only location points? Can you give me the format of the input data?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Changan Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 凌晨5:28
收件人:&nbsp;"vita-epfl/CrowdNav"<CrowdNav@noreply.github.com&gt;;
抄送:&nbsp;"2980785369"<2980785369@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [vita-epfl/CrowdNav] Visible (#20)




@anlanxuan There is no data to download except the repo itself. Validation and test set are just different random seeds.

**Comment by ChanganVR** [comment]
@anlanxuan that's what I meant. There is not really a dataset in the repo. All the trajectories or seeds are hardcoded in the repo/simulation file. I recommend you to take a loot at this file: [](https://github.com/vita-epfl/CrowdNav/blob/master/crowd_sim/envs/crowd_sim.py)
