### ISSUE TITLE
What is the test case on the readme?

### ISSUE THREAD

**Issue by tessavdheiden** [vita-epfl/CrowdNav#22]

**Comment by tessavdheiden** [comment]
The test case 0 seems to be different in my computer (locations of humans is different). 

What one did you use?

**Comment by ChanganVR** [comment]
Hi Tessa,

That command is just a description of how to run the code and doesn't correspond to the navigation demo below. 

And sorry, I don't remember the case number of the navigation demo. But if you generate all of them, you should be able to find it.

Changan
