### ISSUE TITLE
Dose using CPU faster than GPU?

### ISSUE THREAD

**Issue by jiangxkjohn** [vita-epfl/CrowdNav#25]
Hi, I try to train in RTX 2080 but it is too slow and 5000 episodes cost about 18h. The article told that train in CPU just took 10h. I wonder whether the CPU training is the recommanded option. Thank you!

**Comment by ChanganVR** [comment]
Hi John,

Yes, as I mentioned in some previous posts. This code runs faster on CPU probably because of the CPU-intensitve simulation.
