### ISSUE TITLE
Real-world Experiments code

### ISSUE THREAD

**Issue by Geonhee-LEE** [vita-epfl/CrowdNav#28]
Hello, thanks for your contribution about DRL.
I'm interested in mobile robot with DRL. When I read your paper and watched the video you tested using Segway.
Could you open the source for Segway porting source?

Regards.

**Comment by ChanganVR** [comment]
Hi there, sorry currently we don't have any plan to release that code. But as I mentioned in other issues, the idea behind that implementation is simple. You basically need to implement a socket communication between the client and server. And the server in this case would be the desktop (cluster), which listens to the client socket actively and runs the policy.
