### ISSUE TITLE
NameError: name 'orientation_arrows' is not defined

### ISSUE THREAD

**Issue by DDBarBar** [vita-epfl/CrowdNav#3]
Dear prof.Chen
Thank you for getting back to me.  I run this program in my computer.But when I tried to run this command "python test.py --policy sarl --model_dir data/sarl --phase test --visualize --test_case 0", the output "NameError: name 'orientation_arrows' is not defined". I am not sure what should  I do to repair it. Any help is appreciated.
Thanks,
Zhang Di

**Comment by ChanganVR** [comment]
Hi, did you pull the latest master branch? The code works on my computer. And there's not a 'orientation_arrows' name defined in the latest simulation file.
