### ISSUE TITLE
About using the GPU

### ISSUE THREAD

**Issue by luxiaojuntokyo** [vita-epfl/CrowdNav#35]
When I run: python train.py --policy sarl
Every time there will be: INFO: Using device: cpu

I wonder how can I use GPU to speed up the training?

My server's setting, GPU: GTX 1080Ti × 3 (VRAM: 11GB × 3)

Thanks a lot.

**Comment by YuejiangLIU** [comment]
Please try and add the ['--gpu' argument](https://github.com/vita-epfl/CrowdNav/blob/6c4493201e9d892479dfae2ab378bdbec327314f/crowd_nav/train.py#L26) in your command

**Comment by ChanganVR** [comment]
@luxiaojuntokyo the code runs faster on CPU because the speed bottleneck is on CPU-intensive operations. Feel free to explore and optimize the code such that you could use GPU to speed it up.

**Comment by luxiaojuntokyo** [comment]
> @luxiaojuntokyo the code runs faster on CPU because the speed bottleneck is on CPU-intensive operations. Feel free to explore and optimize the code such that you could use GPU to speed it up.

Changan, thank you for your reply. If I get any result, I will comment here.

**Comment by luxiaojuntokyo** [comment]
> Please try and add the ['--gpu' argument](https://github.com/vita-epfl/CrowdNav/blob/6c4493201e9d892479dfae2ab378bdbec327314f/crowd_nav/train.py#L26) in your command

LIU Yuejiang, thank you for your reply.
