### ISSUE TITLE
Adding static obstacles

### ISSUE THREAD

**Issue by FADEAWAY114** [vita-epfl/CrowdNav#66]
How about adding static obstacles to some locations in the environment?

**Comment by ChanganVR** [comment]
This repo does not support adding static obstacles directly. But it shouldn't be too hard to do so and I've seen follow-up papers doing this. You can look up papers that cited this paper.

**Comment by yuqikong** [comment]
Do you know which paper modified the environment and added static obstacles to the environment?

**Comment by yuqikong** [comment]
> This repo does not support adding static obstacles directly. But it shouldn't be too hard to do so and I've seen follow-up papers doing this. You can look up papers that cited this paper.

Do you know which paper modified the environment and added static obstacles to the environment?

**Comment by yuqikong** [comment]
> This repo does not support adding static obstacles directly. But it shouldn't be too hard to do so and I've seen follow-up papers doing this. You can look up papers that cited this paper.

May I ask if you know which paper modified the environment and added static obstacles to the environment, and it is best to add a laser radar.

**Comment by JiayunjieJYJ** [comment]
> > This repo does not support adding static obstacles directly. But it shouldn't be too hard to do so and I've seen follow-up papers doing this. You can look up papers that cited this paper.
> 
> May I ask if you know which paper modified the environment and added static obstacles to the environment, and it is best to add a laser radar.

I have the same question

**Comment by JiayunjieJYJ** [comment]
> This repo does not support adding static obstacles directly. But it shouldn't be too hard to do so and I've seen follow-up papers doing this. You can look up papers that cited this paper.

How to set a human's speed to zero to get a static obstacle?

**Comment by ChanganVR** [comment]
@yuqikong @JiayunjieJYJ a quick search on google scholar that cites this paper gives me this paper: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9341540", I'm sure there are many others.

If you want to set human speed to zero to get a static obstacle, you can check the code here: https://github.com/vita-epfl/CrowdNav/blob/20d678085c06831e658a65b9e20c8bb6f6ecdc10/crowd_sim/envs/crowd_sim.py#L117C16-L142

**Comment by JiayunjieJYJ** [comment]
> @yuqikong @JiayunjieJYJ a quick search on google scholar that cites this paper gives me this paper: "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9341540", I'm sure there are many others.
> 
> If you want to set human speed to zero to get a static obstacle, you can check the code here: https://github.com/vita-epfl/CrowdNav/blob/20d678085c06831e658a65b9e20c8bb6f6ecdc10/crowd_sim/envs/crowd_sim.py#L117C16-L142

Thanks! How to add static obstacles to the ORCA baseline in this code repo?

**Comment by ChanganVR** [comment]
@JiayunjieJYJ it does not matter which policy you are using because you will be changing the simulation environment that equally applies to all policies, which also makes evaluation fair.

**Comment by cocotorrow** [comment]
> How about adding static obstacles to some locations in the environment?
Pls have you solved this problem？

**Comment by EVEREST-dlk** [comment]
> > This repo does not support adding static obstacles directly. But it shouldn't be too hard to do so and I've seen follow-up papers doing this. You can look up papers that cited this paper.
> 
> How to set a human's speed to zero to get a static obstacle?

Have you solved this? I also want to add static obstacles.
