### ISSUE TITLE
questions about 'agent.py'

### ISSUE THREAD

**Issue by LeeKeyu** [vita-epfl/CrowdNav#8]
Hello! I am interested in your fantastic research work and have some questions when reading your code:
In the 'agent.py' (/crowd_sim/envs/utils/), I noticed these lines in the 'get_next_observable_state' function: (when the kinematics is 'unicycle')
            next_vx = action.v * np.cos(**self.theta**)
            next_vy = action.v * np.sin(**self.theta**)
 
My question is why it should be **'self_theta'** ? I mean why the next_vx and next_vy are not computed using the new theta = self.theta + action.r ?
Could you please explain it? Thank you very much!

**Comment by ChanganVR** [comment]
Thank you for pointing out the mistake. After looking at the code, I think it's a bug and I have fixed it. However, this bug doesn't change any results in the paper because all current human policies only have the holonomic constraint.
